### ISSUE TITLE
install the driver on Windows10

### ISSUE THREAD

**Issue by sssxrf** [berndpfrommer/flir_spinnaker_ros2#10]
After I install ros2 successifully on Windows, I tried to install your driver. However, I could not run `wstool` despite I install it with 
`pip install -U rosdep rosinstall_generator wstool rosinstall`
![image](https://user-images.githubusercontent.com/100052475/170089904-44897797-72f4-451d-9763-856bdc275907.png)
The picture below shows that the system could not recognize `wstool`
![image](https://user-images.githubusercontent.com/100052475/170090168-edb91569-f216-4200-a206-266e2e389459.png)

Update: I get it work through
`pip install -U rosdep rosinstall_generator wstool rosinstall
curl --output requirements.txt -L https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows/rosdistro_cache/catkin-requirements.txt
pip install -U --no-deps --force-reinstall -r requirements.txt`

But now I encounter a new problem,
![image](https://user-images.githubusercontent.com/100052475/170095048-3301b90d-2def-4903-8880-9add1dbd491b.png)

**Comment by berndpfrommer** [comment]
Looks like that wstool  install didn't quite work out.
Apologies, but I don't have a windows machine to work on so supporting windows is difficult for me. Even if I had access, I have never really developed on Windows.
This question is probably better asked on the [ROS answers forum](https://answers.ros.org/questions/).

**Comment by berndpfrommer** [comment]
Any progress on this? Can this issue be closed?

**Comment by sssxrf** [comment]
Sorry for the late reply, I'm trying to build my own on Windows 10. But I could not add the FLIR dependencies correctly. I put all the spinnaker files in the 'include' in my packages. However, when I `colcon build  `it, it seems it could not read '.lib' file. Could you please give me some instructions?

**Comment by berndpfrommer** [comment]
Alas I have never developed on Windows. Unless somebody else here can help out, you are on your own. From your other post it did look like you got it to work under Ubuntu, no?

**Comment by sssxrf** [comment]
Yes, it works on Ubuntu. However, I want to do a Windows version. Anyway, thank you for your help.
