### ISSUE TITLE
Spinnaker SDK to ubuntu 22.04?

### ISSUE THREAD

**Issue by maghauke** [berndpfrommer/flir_spinnaker_ros2#16]
Any tips for downloading Spinnaker SDK to ubuntu 22,04? It is only available for ubuntu 20,04 or earlier versions. The readme mentions that the code builds for Ros2 Humble to I guess it is possible...

**Comment by berndpfrommer** [comment]
[Have a look at the Dockerfile here](https://github.com/berndpfrommer/flir_spinnaker_ros2/blob/master/.github/docker/Dockerfile.jammy_humble_spinnaker).
We have continuous integration running on ROS2 humbly on jammy.

I downloaded this version of the spinnaker sdk but it probably also works with more recent ones: spinnaker-2.6.0.157-amd64

You have to [create a fake qt5-package](https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04).

Hope this helps!

**Comment by maghauke** [comment]
Works!
