### ISSUE TITLE
Hardware trigging?

### ISSUE THREAD

**Issue by maghauke** [berndpfrommer/flir_spinnaker_ros2#17]
Anyone who has managed to use this driver along with hardware triggered a Blackfly S Gige camera?

**Comment by berndpfrommer** [comment]
I did, worked for me. Having issues?

**Comment by maghauke** [comment]
Still working with the setup, do you timestamp the camera images with the timestamp from the hardware-trigger-signal? And do you have an example launch file?

**Comment by berndpfrommer** [comment]
I added documentation related to camera hardware synchronization. There actually was already a stereo configuration launch file.
The issue of time stamps is a thorny one. How do you want to get a timestamp from a simple hardware sync pulse?
