### ISSUE TITLE
Do not get any camera_info msgs

### ISSUE THREAD

**Issue by maghauke** [berndpfrommer/flir_spinnaker_ros2#20]
The camera info msgs are not published, any ideas why?

**Comment by berndpfrommer** [comment]
I may not have tested that. Did you provide a valid calibration yaml file?

**Comment by maghauke** [comment]
It should be correct yes, following the yaml format for camerainfo. It also gives no error in the print after launching

**Comment by berndpfrommer** [comment]
Looked at the code: both camerainfo and  image are published in the same call. If the camerainfo is not published it must be due to the ROS camera driver framework suppressing it.

**Comment by maghauke** [comment]
Works now, not sure what the issue was…

**Comment by berndpfrommer** [comment]
closing this for now, please open again if the problem reappears
