### ISSUE TITLE
Throughtput Limit

### ISSUE THREAD

**Issue by DamViv** [berndpfrommer/flir_spinnaker_ros2#21]
Is it possible to limit the bandwidth of each camera with this driver? (as stated [here](https://www.flir.fr/support-center/iis/machine-vision/application-note/usb-3.1-multiple-camera-setup/))
When dealing with multiple cams on a USB3 hub, such a limit is required.
Can we set these values in the config or launch file?

(PS: I'm working with 2 flea3 cameras)

**Comment by berndpfrommer** [comment]
Should be possible, just a matter of getting the config file right. Looking into it.

**Comment by berndpfrommer** [comment]
Have a look at the blackfly_s.cfg. This works for me. The flea may have different node names, so let me know if it works.
