### ISSUE TITLE
package failed: flir_spinnaker_ros2

### ISSUE THREAD

**Issue by sssxrf** [berndpfrommer/flir_spinnaker_ros2#9]
Hi,
I was reported an error while running `colcon build`.
![Screenshot from 2022-05-20 12-38-45](https://user-images.githubusercontent.com/100052475/169573682-bda1a55d-a3e5-439d-857c-ed9a2c090b32.png)
Also, I installed the spinnaker SDK 2.6.0 successfully.
![Screenshot from 2022-05-20 12-40-48](https://user-images.githubusercontent.com/100052475/169573773-0f8e6a50-52ab-41c3-a731-e2d5722476af.png)
Could you please help me out? Thank you so much

**Comment by berndpfrommer** [comment]
What's missing is the camera-info-manager package. There is a way to install all missing dependencies of a workspace, by running *at the top of your workspace*:
```
rosdep install --from-paths src --ignore-src -r -y
```
Could you please run that for me and let me know if that automatically installed the missing camerainfo-manager package?
If yes then I'll include that in the README instructions.

In case the above command fails you can install it manually:
```
sudo apt install ros-galactic-camera-info-manager
```
(or ros-foxy-...., whatever distro you are running on)
But please first try the rosdep line to see if that works. Thanks!

**Comment by sssxrf** [comment]
The rosdep line works. Thank you!

**Comment by berndpfrommer** [comment]
updated documentation
